import {
  sessionAcceptedReplySchema,
  sessionArchiveListReplySchema,
  sessionArchiveListRequestSchema,
  sessionChooseAttachmentsReplySchema,
  sessionChooseAttachmentsRequestSchema,
  sessionCompactRequestSchema,
  sessionDelegationUsageReplySchema,
  sessionDelegationUsageRequestSchema,
  sessionFeedCancelRequestSchema,
  sessionFeedReplySchema,
  sessionFeedRequestSchema,
  sessionHandoffRequestSchema,
  sessionInterruptRequestSchema,
  sessionListReplySchema,
  sessionListRequestSchema,
  sessionPermissionDecisionRequestSchema,
  sessionPermissionReplySchema,
  sessionPermissionRequestSchema,
  sessionQuestionDecisionRequestSchema,
  sessionRenameReplySchema,
  sessionRenameRequestSchema,
  sessionSendRequestSchema,
  sessionShellOutputReplySchema,
  sessionShellOutputRequestSchema,
  sessionStartReplySchema,
  sessionStartRequestSchema,
  sessionStatAttachmentsReplySchema,
  sessionStatAttachmentsRequestSchema,
  sessionTicketConnectRequestSchema,
  sessionTicketDisconnectRequestSchema,
} from './contract'

// One drive table for every CLI (#2030): `start` names its CLI, and the rest carry only a
// sessionId, routed by the Session's owner.
export const SESSION_OPERATIONS = {
  list: {
    name: 'session.list',
    channel: 'argo:session:list',
    request: sessionListRequestSchema,
    reply: sessionListReplySchema,
  },
  archiveList: {
    name: 'session.archive.list',
    channel: 'argo:session:archive:list',
    request: sessionArchiveListRequestSchema,
    reply: sessionArchiveListReplySchema,
  },
  feed: {
    name: 'session.feed',
    channel: 'argo:session:feed',
    request: sessionFeedRequestSchema,
    reply: sessionFeedReplySchema,
  },
  cancelFeed: {
    name: 'session.feed.cancel',
    channel: 'argo:session:feed:cancel',
    request: sessionFeedCancelRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  shellOutput: {
    name: 'session.shell.output',
    channel: 'argo:session:shell:output',
    request: sessionShellOutputRequestSchema,
    reply: sessionShellOutputReplySchema,
  },
  delegationUsage: {
    name: 'session.delegation.usage',
    channel: 'argo:session:delegation:usage',
    request: sessionDelegationUsageRequestSchema,
    reply: sessionDelegationUsageReplySchema,
  },
  rename: {
    name: 'session.rename',
    channel: 'argo:session:rename',
    request: sessionRenameRequestSchema,
    reply: sessionRenameReplySchema,
  },
  start: {
    name: 'session.start',
    channel: 'argo:session:start',
    request: sessionStartRequestSchema,
    reply: sessionStartReplySchema,
  },
  send: {
    name: 'session.send',
    channel: 'argo:session:send',
    request: sessionSendRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  interrupt: {
    name: 'session.interrupt',
    channel: 'argo:session:interrupt',
    request: sessionInterruptRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  compact: {
    name: 'session.compact',
    channel: 'argo:session:compact',
    request: sessionCompactRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  handoff: {
    name: 'session.handoff',
    channel: 'argo:session:handoff',
    request: sessionHandoffRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  readPermission: {
    name: 'session.permission',
    channel: 'argo:session:permission',
    request: sessionPermissionRequestSchema,
    reply: sessionPermissionReplySchema,
  },
  decidePermission: {
    name: 'session.permission.decide',
    channel: 'argo:session:permission:decide',
    request: sessionPermissionDecisionRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  decideQuestion: {
    name: 'session.question.decide',
    channel: 'argo:session:question:decide',
    request: sessionQuestionDecisionRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  chooseAttachments: {
    name: 'session.attachments.choose',
    channel: 'argo:session:attachments:choose',
    request: sessionChooseAttachmentsRequestSchema,
    reply: sessionChooseAttachmentsReplySchema,
  },
  statAttachments: {
    name: 'session.attachments.stat',
    channel: 'argo:session:attachments:stat',
    request: sessionStatAttachmentsRequestSchema,
    reply: sessionStatAttachmentsReplySchema,
  },
  connectTicket: {
    name: 'session.ticket.connect',
    channel: 'argo:session:ticket:connect',
    request: sessionTicketConnectRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  disconnectTicket: {
    name: 'session.ticket.disconnect',
    channel: 'argo:session:ticket:disconnect',
    request: sessionTicketDisconnectRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
} as const
