// The --text-* roles declared in tokens.css. Hand-edited: keep it in step with the contract.
export const TEXT_SIZES = [
  'badge',
  'base',
  'body',
  'body-tracking',
  'body-weight',
  'code',
  'code-tracking',
  'code-weight',
  'control',
  'control-tracking',
  'control-weight',
  'heading',
  'heading-tracking',
  'heading-weight',
  'meta',
  'meta-tracking',
  'meta-weight',
  'prose',
  'prose-tracking',
  'prose-weight',
  'sm',
  'title',
  'title-tracking',
  'title-weight',
  'xs',
] as const
