import type { OnboardingRecommendation } from './onboarding-model'

export const PROJECT_RECOMMENDATIONS: OnboardingRecommendation[] = [
  {
    accepted: true,
    copyKey: 'rtk-filters',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/blob/main/.rtk/filters.toml',
    id: 'rtk-filters',
    icon: 'terminal',
    kind: 'action',
  },
  {
    accepted: true,
    copyKey: 'quality-gates',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/tree/main/packages/argo-skills/skills/setup-quality-gates',
    id: 'quality-gates',
    icon: 'quality',
    kind: 'action',
  },
  {
    accepted: true,
    copyKey: 'agent-instructions',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/tree/main/packages/argo-skills/skills/setup-argo-skills/templates',
    id: 'agent-instructions',
    icon: 'project-docs',
    kind: 'action',
  },
  {
    accepted: true,
    copyKey: 'guardrail-hooks',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/blob/main/hooks.json',
    id: 'guardrail-hooks',
    icon: 'guards',
    kind: 'action',
  },
  {
    accepted: true,
    copyKey: 'interface-review',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/tree/main/packages/argo-skills/skills/interface-review',
    id: 'interface-review',
    icon: 'interface-review',
    kind: 'action',
  },
  {
    accepted: false,
    copyKey: 'visual-direction',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/tree/main/packages/argo-skills/skills/visual-exploration',
    id: 'visual-direction',
    icon: 'visual-direction',
    kind: 'action',
  },
  {
    accepted: true,
    copyKey: 'agent-doc-audit',
    group: 'project-files',
    href: 'https://github.com/milad-alizadeh/argo/tree/main/packages/argo-skills/skills/audit-agent-docs',
    id: 'agent-doc-audit',
    icon: 'audit',
    kind: 'action',
  },
]
