// Generated by `bun run recordings:sync`; refreshed after `record:vendor-history`.
import recordedClaudeAgentsSource from './claude-cli/2.1.286/agents.json' with { type: 'json' }
import recordedClaudeCompactionChainSource from './claude-cli/2.1.286/compaction-chain.json' with {
  type: 'json',
}
import recordedClaudeLifecycleFramesSource from './claude-cli/2.1.286/lifecycle-frames.json' with {
  type: 'json',
}
import { claudeRecording as recordedClaudeHistorySource } from './claude-cli/2.1.286/session-history-claude'
import recordedClaudeCommandsSource from './claude-cli/2.1.286/supported-commands.json' with {
  type: 'json',
}
import { loadRecording, recordingLocation } from './recording'
export const CLAUDE_RECORDING_VERSION = recordingLocation('claude-cli/2.1.286/version').version
export const recordedClaudeAgents = loadRecording(
  'claude-cli/2.1.286/agents.json',
  recordedClaudeAgentsSource,
).payload
export const recordedClaudeCompactionChain = loadRecording(
  'claude-cli/2.1.286/compaction-chain.json',
  recordedClaudeCompactionChainSource,
).payload
export const recordedClaudeLifecycleFrames = loadRecording(
  'claude-cli/2.1.286/lifecycle-frames.json',
  recordedClaudeLifecycleFramesSource,
).payload
export const recordedClaudeHistory = loadRecording(
  'claude-cli/2.1.286/session-history-claude.ts',
  recordedClaudeHistorySource,
)
export const recordedClaudeCommands = loadRecording(
  'claude-cli/2.1.286/supported-commands.json',
  recordedClaudeCommandsSource,
).payload
