// Generated by `bun run recordings:sync`; refreshed after `record:vendor-history`.
import recordedAcpDiscoverySource from './claude-acp/0.84.0/session-discovery.json' with {
  type: 'json',
}
import { loadRecording } from './recording'
export const recordedAcpDiscovery = loadRecording(
  'claude-acp/0.84.0/session-discovery.json',
  recordedAcpDiscoverySource,
).payload
