// Generated by `bun run recordings:sync`; refreshed after `record:vendor-history`.
import recordedCodexExternalThreadsSource from './codex-app-server/0.157.0/external-threads.json' with {
  type: 'json',
}
import recordedCodexHooksSource from './codex-app-server/0.157.0/hooks.json' with { type: 'json' }
import recordedCodexFileChangesSource from './codex-app-server/0.157.0/live-file-change.json' with {
  type: 'json',
}
import recordedCodexNotificationsSource from './codex-app-server/0.157.0/live-notifications.json' with {
  type: 'json',
}
import recordedCodexModelsSource from './codex-app-server/0.157.0/model-list.json' with {
  type: 'json',
}
import recordedCodexSessionSyncSource from './codex-app-server/0.157.0/session-sync.json' with {
  type: 'json',
}
import recordedCodexSkillsSource from './codex-app-server/0.157.0/skills-list.json' with {
  type: 'json',
}
import { codexRecording as recordedCodexHistorySource } from './codex-app-server/0.157.0/thread-history-codex'
import recordedCodexSubagentsSource from './codex-app-server/0.157.0/thread-read-subagents.json' with {
  type: 'json',
}
import { loadRecording, recordingLocation } from './recording'
export const CODEX_RECORDING_VERSION = recordingLocation('codex-app-server/0.157.0/version').version
export const recordedCodexExternalThreads = loadRecording(
  'codex-app-server/0.157.0/external-threads.json',
  recordedCodexExternalThreadsSource,
).payload
export const recordedCodexHooks = loadRecording(
  'codex-app-server/0.157.0/hooks.json',
  recordedCodexHooksSource,
).payload
export const recordedCodexFileChanges = loadRecording(
  'codex-app-server/0.157.0/live-file-change.json',
  recordedCodexFileChangesSource,
).payload
export const recordedCodexNotifications = loadRecording(
  'codex-app-server/0.157.0/live-notifications.json',
  recordedCodexNotificationsSource,
).payload
export const recordedCodexModels = loadRecording(
  'codex-app-server/0.157.0/model-list.json',
  recordedCodexModelsSource,
).payload
export const recordedCodexSessionSync = loadRecording(
  'codex-app-server/0.157.0/session-sync.json',
  recordedCodexSessionSyncSource,
).payload
export const recordedCodexSkills = loadRecording(
  'codex-app-server/0.157.0/skills-list.json',
  recordedCodexSkillsSource,
).payload
export const recordedCodexHistory = loadRecording(
  'codex-app-server/0.157.0/thread-history-codex.ts',
  recordedCodexHistorySource,
)
export const recordedCodexSubagents = loadRecording(
  'codex-app-server/0.157.0/thread-read-subagents.json',
  recordedCodexSubagentsSource,
).payload
