// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from '../absolute-path-buf'
import type { OverriddenMetadata } from './overridden-metadata'
import type { WriteStatus } from './write-status'

export type ConfigWriteResponse = {
  status: WriteStatus
  version: string
  /**
   * Canonical path to the config file that was written.
   */
  filePath: AbsolutePathBuf
  overriddenMetadata: OverriddenMetadata | null
}
