// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from '../serde_json/json-value'
import type { ConfigLayerSource } from './config-layer-source'

export type ConfigLayer = {
  name: ConfigLayerSource
  version: string
  config: JsonValue
  disabledReason: string | null
}
