// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchChangeKind } from './patch-change-kind'

export type FileUpdateChange = { path: string; kind: PatchChangeKind; diff: string }
