// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from '../serde_json/json-value'
import type { ConfigLayerMetadata } from './config-layer-metadata'

export type OverriddenMetadata = {
  message: string
  overridingLayer: ConfigLayerMetadata
  effectiveValue: JsonValue
}
