// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from '../absolute-path-buf'
import type { SkillDependencies } from './skill-dependencies'
import type { SkillInterface } from './skill-interface'
import type { SkillScope } from './skill-scope'

export type SkillMetadata = {
  name: string
  description: string
  /**
   * Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.
   */
  shortDescription?: string
  interface?: SkillInterface
  dependencies?: SkillDependencies
  path: AbsolutePathBuf
  scope: SkillScope
  enabled: boolean
  /**
   * Owning plugin ID, matching `PluginSummary.id`, when known.
   */
  pluginId: string | null
}
