// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillToolDependency } from './skill-tool-dependency'

export type SkillDependencies = { tools: Array<SkillToolDependency> }
