// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionCallOutputBody } from '../function-call-output-body'
import type { ImageGenerationItem } from '../image-generation-item'
import type { LegacyAppPathString } from '../legacy-app-path-string'
import type { MessagePhase } from '../message-phase'
import type { ReasoningEffort } from '../reasoning-effort'
import type { JsonValue } from '../serde_json/json-value'
import type { SleepItem } from '../sleep-item'
import type { WebSearchItem } from '../web-search-item'
import type { AgentMessageDelivery } from './agent-message-delivery'
import type { AsyncUserInputQuestion } from './async-user-input-question'
import type { CollabAgentState } from './collab-agent-state'
import type { CollabAgentTool } from './collab-agent-tool'
import type { CollabAgentToolCallStatus } from './collab-agent-tool-call-status'
import type { CommandAction } from './command-action'
import type { CommandExecutionSource } from './command-execution-source'
import type { CommandExecutionStatus } from './command-execution-status'
import type { DynamicToolCallOutputContentItem } from './dynamic-tool-call-output-content-item'
import type { DynamicToolCallStatus } from './dynamic-tool-call-status'
import type { FileUpdateChange } from './file-update-change'
import type { HookPromptFragment } from './hook-prompt-fragment'
import type { McpAppUi } from './mcp-app-ui'
import type { McpToolCallAppContext } from './mcp-tool-call-app-context'
import type { McpToolCallError } from './mcp-tool-call-error'
import type { McpToolCallResult } from './mcp-tool-call-result'
import type { McpToolCallStatus } from './mcp-tool-call-status'
import type { MemoryCitation } from './memory-citation'
import type { PatchApplyStatus } from './patch-apply-status'
import type { SubAgentActivityKind } from './sub-agent-activity-kind'
import type { UserInput } from './user-input'

export type ThreadItem =
  | { type: 'userMessage'; id: string; clientId: string | null; content: Array<UserInput> }
  | { type: 'hookPrompt'; id: string; fragments: Array<HookPromptFragment> }
  | {
      type: 'agentMessage'
      id: string
      text: string
      phase: MessagePhase | null
      memoryCitation: MemoryCitation | null
      delivery: AgentMessageDelivery | null
      questions: Array<AsyncUserInputQuestion> | null
    }
  | {
      type: 'functionCallOutput'
      id: string
      name: string
      namespace: string | null
      output: FunctionCallOutputBody
    }
  | { type: 'plan'; id: string; text: string }
  | { type: 'reasoning'; id: string; summary: Array<string>; content: Array<string> }
  | {
      type: 'commandExecution'
      id: string
      /**
       * Trusted first-party plugin id when this command resolves to one plugin script.
       */
      pluginId: string | null
      /**
       * Safe plugin-relative path when this command resolves to one plugin script.
       */
      scriptPath: string | null
      /**
       * The command to be executed.
       */
      command: string
      /**
       * The command's working directory.
       */
      cwd: LegacyAppPathString
      /**
       * Identifier for the underlying PTY process (when available).
       */
      processId: string | null
      source: CommandExecutionSource
      status: CommandExecutionStatus
      /**
       * A best-effort parsing of the command to understand the action(s) it will perform.
       * This returns a list of CommandAction objects because a single shell command may
       * be composed of many commands piped together.
       */
      commandActions: Array<CommandAction>
      /**
       * The command's output, aggregated from stdout and stderr.
       */
      aggregatedOutput: string | null
      /**
       * The command's exit code.
       */
      exitCode: number | null
      /**
       * The duration of the command execution in milliseconds.
       */
      durationMs: number | null
    }
  | { type: 'fileChange'; id: string; changes: Array<FileUpdateChange>; status: PatchApplyStatus }
  | {
      type: 'mcpToolCall'
      id: string
      server: string
      tool: string
      status: McpToolCallStatus
      arguments: JsonValue
      appContext: McpToolCallAppContext | null
      /**
       * Legacy compatibility field; prefer `mcpAppUi.resourceUri` when available.
       */
      mcpAppResourceUri?: string
      /**
       * Presentation captured from the invoked descriptor; absent in older history.
       */
      mcpAppUi: McpAppUi | null
      pluginId: string | null
      readOnlyHint: boolean | null
      result: McpToolCallResult | null
      error: McpToolCallError | null
      /**
       * The duration of the MCP tool call in milliseconds.
       */
      durationMs: number | null
    }
  | {
      type: 'dynamicToolCall'
      id: string
      namespace: string | null
      tool: string
      arguments: JsonValue
      status: DynamicToolCallStatus
      contentItems: Array<DynamicToolCallOutputContentItem> | null
      success: boolean | null
      /**
       * The duration of the dynamic tool call in milliseconds.
       */
      durationMs: number | null
    }
  | {
      type: 'collabAgentToolCall'
      /**
       * Unique identifier for this collab tool call.
       */
      id: string
      /**
       * Name of the collab tool that was invoked.
       */
      tool: CollabAgentTool
      /**
       * Current status of the collab tool call.
       */
      status: CollabAgentToolCallStatus
      /**
       * Thread ID of the agent issuing the collab request.
       */
      senderThreadId: string
      /**
       * Thread ID of the receiving agent, when applicable. In case of spawn operation,
       * this corresponds to the newly spawned agent.
       */
      receiverThreadIds: Array<string>
      /**
       * Prompt text sent as part of the collab tool call, when available.
       */
      prompt: string | null
      /**
       * Model requested for the spawned agent, when applicable.
       */
      model: string | null
      /**
       * Reasoning effort requested for the spawned agent, when applicable.
       */
      reasoningEffort: ReasoningEffort | null
      /**
       * Last known status of the target agents, when available.
       */
      agentsStates: { [key in string]?: CollabAgentState }
    }
  | {
      type: 'subAgentActivity'
      id: string
      kind: SubAgentActivityKind
      agentThreadId: string
      agentPath: string
    }
  | ({ type: 'webSearch' } & WebSearchItem)
  | { type: 'imageView'; id: string; path: LegacyAppPathString }
  | ({ type: 'sleep' } & SleepItem)
  | ({ type: 'imageGeneration' } & ImageGenerationItem)
  | { type: 'enteredReviewMode'; id: string; review: string }
  | { type: 'exitedReviewMode'; id: string; review: string }
  | { type: 'contextCompaction'; id: string }
