import { SESSION_ARCHIVE_SEARCH_OPERATIONS } from '@/domains/sessions/contract/ipc/archive-search-operations'
import {
  sessionAcceptedReplySchema,
  sessionChooseAttachmentsReplySchema,
  sessionChooseAttachmentsRequestSchema,
  sessionCompactRequestSchema,
  sessionHandoffRequestSchema,
  sessionInterruptRequestSchema,
  sessionListReplySchema,
  sessionListRequestSchema,
  sessionPermissionDecisionRequestSchema,
  sessionPermissionReplySchema,
  sessionPermissionRequestSchema,
  sessionQuestionDecisionRequestSchema,
  sessionRenameReplySchema,
  sessionRenameRequestSchema,
  sessionSendRequestSchema,
  sessionShellOutputReplySchema,
  sessionShellOutputRequestSchema,
  sessionStartReplySchema,
  sessionStartRequestSchema,
  sessionStatAttachmentsReplySchema,
  sessionStatAttachmentsRequestSchema,
  sessionSteerRequestSchema,
  sessionSubagentUsageReplySchema,
  sessionSubagentUsageRequestSchema,
  sessionTicketConnectRequestSchema,
  sessionTicketDisconnectRequestSchema,
} from '@/domains/sessions/contract/ipc/contract'
import { SESSION_READ_OPERATIONS } from '@/domains/sessions/contract/ipc/read-operations'
import { SESSION_UNREAD_OPERATIONS } from '@/domains/sessions/contract/ipc/unread-operations'

// One drive table for every Harness (#2030): `start` names its Harness, and the rest carry only a
// sessionId, routed by the Session's owner.
export const SESSION_OPERATIONS = {
  list: {
    name: 'session.list',
    channel: 'argo:session:list',
    request: sessionListRequestSchema,
    reply: sessionListReplySchema,
  },
  ...SESSION_ARCHIVE_SEARCH_OPERATIONS,
  ...SESSION_READ_OPERATIONS,
  ...SESSION_UNREAD_OPERATIONS,
  shellOutput: {
    name: 'session.shell.output',
    channel: 'argo:session:shell:output',
    request: sessionShellOutputRequestSchema,
    reply: sessionShellOutputReplySchema,
  },
  subagentUsage: {
    name: 'session.subagent.usage',
    channel: 'argo:session:subagent:usage',
    request: sessionSubagentUsageRequestSchema,
    reply: sessionSubagentUsageReplySchema,
  },
  rename: {
    name: 'session.rename',
    channel: 'argo:session:rename',
    request: sessionRenameRequestSchema,
    reply: sessionRenameReplySchema,
  },
  start: {
    name: 'session.start',
    channel: 'argo:session:start',
    request: sessionStartRequestSchema,
    reply: sessionStartReplySchema,
  },
  send: {
    name: 'session.send',
    channel: 'argo:session:send',
    request: sessionSendRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  steer: {
    name: 'session.steer',
    channel: 'argo:session:steer',
    request: sessionSteerRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  interrupt: {
    name: 'session.interrupt',
    channel: 'argo:session:interrupt',
    request: sessionInterruptRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  compact: {
    name: 'session.compact',
    channel: 'argo:session:compact',
    request: sessionCompactRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  handoff: {
    name: 'session.handoff',
    channel: 'argo:session:handoff',
    request: sessionHandoffRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  readPermission: {
    name: 'session.permission',
    channel: 'argo:session:permission',
    request: sessionPermissionRequestSchema,
    reply: sessionPermissionReplySchema,
  },
  decidePermission: {
    name: 'session.permission.decide',
    channel: 'argo:session:permission:decide',
    request: sessionPermissionDecisionRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  decideQuestion: {
    name: 'session.question.decide',
    channel: 'argo:session:question:decide',
    request: sessionQuestionDecisionRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  chooseAttachments: {
    name: 'session.attachments.choose',
    channel: 'argo:session:attachments:choose',
    request: sessionChooseAttachmentsRequestSchema,
    reply: sessionChooseAttachmentsReplySchema,
  },
  statAttachments: {
    name: 'session.attachments.stat',
    channel: 'argo:session:attachments:stat',
    request: sessionStatAttachmentsRequestSchema,
    reply: sessionStatAttachmentsReplySchema,
  },
  connectTicket: {
    name: 'session.ticket.connect',
    channel: 'argo:session:ticket:connect',
    request: sessionTicketConnectRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
  disconnectTicket: {
    name: 'session.ticket.disconnect',
    channel: 'argo:session:ticket:disconnect',
    request: sessionTicketDisconnectRequestSchema,
    reply: sessionAcceptedReplySchema,
  },
} as const
