import { execFileSync } from 'node:child_process'
import { readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const producers = [
  {
    name: 'codex-app-server',
    prefix: 'CODEX',
    files: {
      'external-threads.json': 'recordedCodexExternalThreads',
      'hooks.json': 'recordedCodexHooks',
      'live-file-change.json': 'recordedCodexFileChanges',
      'live-notifications.json': 'recordedCodexNotifications',
      'model-list.json': 'recordedCodexModels',
      'session-sync.json': 'recordedCodexSessionSync',
      'skills-list.json': 'recordedCodexSkills',
      'thread-history-codex.ts': 'recordedCodexHistory',
      'thread-read-subagents.json': 'recordedCodexSubagents',
    },
  },
  {
    name: 'claude-cli',
    prefix: 'CLAUDE',
    files: {
      'agents.json': 'recordedClaudeAgents',
      'lifecycle-frames.json': 'recordedClaudeLifecycleFrames',
      'session-history-claude.ts': 'recordedClaudeHistory',
      'supported-commands.json': 'recordedClaudeCommands',
    },
  },
  {
    name: 'claude-acp',
    prefix: 'ACP',
    files: {
      'session-discovery.json': 'recordedAcpDiscovery',
    },
  },
] as const

type Producer = (typeof producers)[number]
const root = path.resolve('mocks/recordings')

async function recordingDirectory(producer: Producer) {
  const entries = await readdir(path.join(root, producer.name), { withFileTypes: true })
  const versions = entries
    .filter((entry) => entry.isDirectory() && /^\d+\.\d+\.\d+$/.test(entry.name))
    .map((entry) => entry.name)
    .sort((first, second) => first.localeCompare(second, 'en', { numeric: true }))
  const version = versions.at(-1)
  if (!version) throw new Error(`No version folder for ${producer.name}.`)
  const directory = `${producer.name}/${version}`
  const files = await readdir(path.join(root, directory))
  const missing = Object.keys(producer.files).filter((file) => !files.includes(file))
  if (missing.length)
    throw new Error(
      `Incomplete recording folder ${directory}: ${missing.join(', ')}. Record the missing responses before refreshing imports.`,
    )
  return directory
}

async function producerSource(producer: Producer) {
  const directory = await recordingDirectory(producer)
  const imports: string[] = []
  const exports: string[] = []
  for (const [file, name] of Object.entries(producer.files)) {
    const local = `${name}Source`
    const relative = `${directory}/${file}`
    if (file.endsWith('.json')) {
      imports.push(`import ${local} from './${relative}' with { type: 'json' }`)
      exports.push(`export const ${name} = loadRecording('${relative}', ${local}).payload`)
    } else {
      const symbol = producer.name === 'claude-cli' ? 'claudeRecording' : 'codexRecording'
      imports.push(`import { ${symbol} as ${local} } from './${relative.slice(0, -3)}'`)
      exports.push(`export const ${name} = loadRecording('${relative}', ${local})`)
    }
  }
  const metadata =
    producer.prefix === 'ACP'
      ? []
      : [
          `export const ${producer.prefix}_RECORDING_VERSION = recordingLocation('${directory}/version').version`,
        ]
  return [
    '// Generated by `bun run recordings:sync`; refreshed after `record:vendor-history`.',
    ...imports,
    `import { loadRecording${metadata.length ? ', recordingLocation' : ''} } from './recording'`,
    ...metadata,
    ...exports,
    '',
  ].join('\n')
}

const outputs = []
for (const producer of producers) {
  outputs.push({
    file: path.join(root, `${producer.name}.ts`),
    source: await producerSource(producer),
  })
}
for (const { file, source } of outputs) await writeFile(file, source)
execFileSync('bunx', ['biome', 'check', '--write', ...outputs.map(({ file }) => file)], {
  stdio: 'inherit',
})
