export { claudeHarness } from './session-harness'
export type { ResumeTarget } from './channel/drive-channel'
export type { LiveMessage } from './channel/live-messages'
export type { CompanionPart } from './channel/companion-plugin'
export { CYCLE_MODE, REDRAW } from './turn/claude-setup'
export type { ClaudePermissionGate } from './permission/permission-gate'
export { createClaudeSessionDriver } from './claude-session-driver'
export { createHandoffLedger } from './handoff/handoff-ledger'
export type { HandoffLedger } from './handoff/handoff-ledger'
