import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const repositoryRoot = path.resolve(import.meta.dirname, '..')
const contractPath = path.join(repositoryRoot, 'apps/desktop/src/platform/renderer/tokens.css')
const outputPath = path.join(repositoryRoot, 'apps/desktop/src/platform/renderer/lib/text-sizes.ts')

export function textSizes(contract: string): string[] {
  const declared = [...contract.matchAll(/^\s*--text-([a-z0-9-]+):/gm)]
    .map(([, name]) => name)
    .filter((name): name is string => name !== undefined)
  return [...new Set(declared)].filter((name) => !name.includes('--')).sort()
}

export function textSizeSource(contract: string): string {
  const entries = textSizes(contract)
    .map((name) => `  '${name}',`)
    .join('\n')
  return `// GENERATED by scripts/design-token-class-groups.mts. Edit tokens.css, not this file.\nexport const TEXT_SIZES = [\n${entries}\n] as const\n`
}

if (process.argv[1] === import.meta.filename) {
  writeFileSync(outputPath, textSizeSource(readFileSync(contractPath, 'utf8')))
  process.stdout.write(`wrote ${path.relative(repositoryRoot, outputPath)}\n`)
}
