/// Why a Map file could not be read (#1145).
///
/// Every case is a value the reader can act on rather than a trap: a map file is generated by a
/// program, written to per-machine app data and read again much later, so the version that wrote
/// it may be older than the version reading it, and the bytes may be half a write. The reader's
/// answer to all four is the same — say the measurement could not be read, and offer a rebuild —
/// but the cases stay apart because the log is what says which one happened.
public enum AtlasMapError: Error, Equatable {
    /// The bytes are not a Map file at all. Carries the decoder's own account, for the log.
    case unreadable(String)

    /// A Map file from a version of the format this reader does not know.
    case unsupportedVersion(Int)

    /// A node whose name cannot make a path — empty, or holding the separator itself. Carries the
    /// path of the node that holds it, which is the only thing that can locate it in a nested file.
    case unnamedNode(inside: String)

    /// Two nodes on one Plate with the same name, which is one path naming two files.
    case repeatedName(String)

    /// A node labelled one kind and carrying the other's contents — a Plot holding children, or
    /// a Plate holding measures. Refused rather than read past, because reading past a mislabelled
    /// folder takes every file under it off the map with nothing saying one went missing.
    case contradictoryNode(String)

    /// A node whose path is not the one the Plate it stands on gives it. A write-side failure: a
    /// caller can build such a tree in memory, and writing it would re-parent the subtree.
    case misplacedNode(String)

    /// The Map in hand cannot be written out. JSON has no literal for a measure that is not a
    /// finite number, so a generator that divided by zero is caught here rather than at the read.
    case unwritable(String)
}
