// THROWAWAY PROTOTYPE (#2464): shared development gate and hash-query contract.
export const PROJECT_ONBOARDING_PROTOTYPE_ENV = 'ARGO_PROJECT_ONBOARDING_PROTOTYPE'
export const PROJECT_ONBOARDING_PROTOTYPE_KEY = 'prototype'
export const PROJECT_ONBOARDING_PROTOTYPE_VALUE = 'project-onboarding'
export const PROJECT_ONBOARDING_VARIANT_KEY = 'variant'
export const PROJECT_ONBOARDING_DEFAULT_VARIANT = 'A'

export const PROJECT_ONBOARDING_PROTOTYPE_HASH =
  `#/sessions?${PROJECT_ONBOARDING_PROTOTYPE_KEY}=${PROJECT_ONBOARDING_PROTOTYPE_VALUE}` +
  `&${PROJECT_ONBOARDING_VARIANT_KEY}=${PROJECT_ONBOARDING_DEFAULT_VARIANT}`
